"""criar_novo_db

Revision ID: 49d20ac6fa3a
Revises: 
Create Date: 2023-08-23 09:11:04.116880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d20ac6fa3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastro_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('sobrenome', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('senha', sa.String(length=18), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('telefone', sa.String(length=13), nullable=False),
    sa.Column('endereco', sa.String(length=60), nullable=False),
    sa.Column('bairro', sa.String(length=60), nullable=False),
    sa.Column('cidade', sa.String(length=60), nullable=False),
    sa.Column('uf', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contato_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('telefone', sa.String(length=14), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contato_model')
    op.drop_table('cadastro_model')
    # ### end Alembic commands ###
